# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class AgentServiceStub(object):
    """============ СЕРВИС ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSchedule = channel.unary_unary(
                '/agent.AgentService/GenerateSchedule',
                request_serializer=agent__pb2.GenerateRequest.SerializeToString,
                response_deserializer=agent__pb2.GenerateResponse.FromString,
                )
        self.GetGenerationStatus = channel.unary_unary(
                '/agent.AgentService/GetGenerationStatus',
                request_serializer=agent__pb2.StatusRequest.SerializeToString,
                response_deserializer=agent__pb2.StatusResponse.FromString,
                )
        self.GetGenerationHistory = channel.unary_unary(
                '/agent.AgentService/GetGenerationHistory',
                request_serializer=agent__pb2.HistoryRequest.SerializeToString,
                response_deserializer=agent__pb2.HistoryResponse.FromString,
                )
        self.StopGeneration = channel.unary_unary(
                '/agent.AgentService/StopGeneration',
                request_serializer=agent__pb2.StopRequest.SerializeToString,
                response_deserializer=agent__pb2.StopResponse.FromString,
                )
        self.GetCourseLoads = channel.unary_unary(
                '/agent.AgentService/GetCourseLoads',
                request_serializer=agent__pb2.GetCourseLoadsRequest.SerializeToString,
                response_deserializer=agent__pb2.CourseLoadsResponse.FromString,
                )
        self.GetSchedule = channel.unary_unary(
                '/agent.AgentService/GetSchedule',
                request_serializer=agent__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=agent__pb2.ScheduleResponse.FromString,
                )
        self.GetScheduleForGroup = channel.unary_unary(
                '/agent.AgentService/GetScheduleForGroup',
                request_serializer=agent__pb2.GroupScheduleRequest.SerializeToString,
                response_deserializer=agent__pb2.ScheduleResponse.FromString,
                )
        self.GetScheduleForTeacher = channel.unary_unary(
                '/agent.AgentService/GetScheduleForTeacher',
                request_serializer=agent__pb2.TeacherScheduleRequest.SerializeToString,
                response_deserializer=agent__pb2.ScheduleResponse.FromString,
                )
        self.AnalyzeSchedule = channel.unary_unary(
                '/agent.AgentService/AnalyzeSchedule',
                request_serializer=agent__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=agent__pb2.AnalysisResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/agent.AgentService/GetMetrics',
                request_serializer=agent__pb2.MetricsRequest.SerializeToString,
                response_deserializer=agent__pb2.MetricsResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/agent.AgentService/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                )


class AgentServiceServicer(object):
    """============ СЕРВИС ============

    """

    def GenerateSchedule(self, request, context):
        """Генерация расписания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenerationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenerationHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseLoads(self, request, context):
        """Управление нагрузкой
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Расписание
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleForTeacher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSchedule(self, request, context):
        """Аналитика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSchedule,
                    request_deserializer=agent__pb2.GenerateRequest.FromString,
                    response_serializer=agent__pb2.GenerateResponse.SerializeToString,
            ),
            'GetGenerationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenerationStatus,
                    request_deserializer=agent__pb2.StatusRequest.FromString,
                    response_serializer=agent__pb2.StatusResponse.SerializeToString,
            ),
            'GetGenerationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenerationHistory,
                    request_deserializer=agent__pb2.HistoryRequest.FromString,
                    response_serializer=agent__pb2.HistoryResponse.SerializeToString,
            ),
            'StopGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.StopGeneration,
                    request_deserializer=agent__pb2.StopRequest.FromString,
                    response_serializer=agent__pb2.StopResponse.SerializeToString,
            ),
            'GetCourseLoads': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseLoads,
                    request_deserializer=agent__pb2.GetCourseLoadsRequest.FromString,
                    response_serializer=agent__pb2.CourseLoadsResponse.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=agent__pb2.GetScheduleRequest.FromString,
                    response_serializer=agent__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetScheduleForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleForGroup,
                    request_deserializer=agent__pb2.GroupScheduleRequest.FromString,
                    response_serializer=agent__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetScheduleForTeacher': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleForTeacher,
                    request_deserializer=agent__pb2.TeacherScheduleRequest.FromString,
                    response_serializer=agent__pb2.ScheduleResponse.SerializeToString,
            ),
            'AnalyzeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSchedule,
                    request_deserializer=agent__pb2.AnalyzeRequest.FromString,
                    response_serializer=agent__pb2.AnalysisResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=agent__pb2.MetricsRequest.FromString,
                    response_serializer=agent__pb2.MetricsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """============ СЕРВИС ============

    """

    @staticmethod
    def GenerateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GenerateSchedule',
            agent__pb2.GenerateRequest.SerializeToString,
            agent__pb2.GenerateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGenerationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetGenerationStatus',
            agent__pb2.StatusRequest.SerializeToString,
            agent__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGenerationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetGenerationHistory',
            agent__pb2.HistoryRequest.SerializeToString,
            agent__pb2.HistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/StopGeneration',
            agent__pb2.StopRequest.SerializeToString,
            agent__pb2.StopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCourseLoads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetCourseLoads',
            agent__pb2.GetCourseLoadsRequest.SerializeToString,
            agent__pb2.CourseLoadsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetSchedule',
            agent__pb2.GetScheduleRequest.SerializeToString,
            agent__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScheduleForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetScheduleForGroup',
            agent__pb2.GroupScheduleRequest.SerializeToString,
            agent__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScheduleForTeacher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetScheduleForTeacher',
            agent__pb2.TeacherScheduleRequest.SerializeToString,
            agent__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/AnalyzeSchedule',
            agent__pb2.AnalyzeRequest.SerializeToString,
            agent__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/GetMetrics',
            agent__pb2.MetricsRequest.SerializeToString,
            agent__pb2.MetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.AgentService/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
